In [14]:
import torch
x=torch.tensor(3.0)
y=torch.tensor(4)
print(x*y)
a1 = torch.arange(12).reshape(3,4)
print(a1, len(a1), a1.T, a1.shape, a1.shape[1])
print(a1.sum()) #全部加起来

tensor(12.)
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) 3 tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]) torch.Size([3, 4]) 4
tensor(66)


In [4]:
import torch
import numpy as np

x=torch.tensor([[1,2,3,4],[5,6,7,8]])
print(x.numpy())

#随便准备一个网络输入
y = np.array([[3.1, 1.3, 1.2],
              [2.1, 1.3, 13]])
print(y)
z = torch.FloatTensor(y)
print(z)



[[1 2 3 4]
 [5 6 7 8]]
[[ 3.1  1.3  1.2]
 [ 2.1  1.3 13. ]]
tensor([[ 3.1000,  1.3000,  1.2000],
        [ 2.1000,  1.3000, 13.0000]])


In [11]:
import torch
x = torch.Tensor([[1,2], [3,4]])
y = torch.Tensor([[1,2], [3,4]])
print(x * y)


tensor([[ 1.,  4.],
        [ 9., 16.]])


In [7]:
import numpy as np
x = np.array([[1,2,3], 
              [4,5,6]])
y = np.array([[1,2,3], 
              [4,5,6]])
z = np.dot(x,y.T)
a = np.dot(x.T,y)
print(z)
print(a)


[[14 32]
 [32 77]]
[[17 22 27]
 [22 29 36]
 [27 36 45]]


In [10]:
import torch
import numpy as np

x = torch.Tensor([0.3, 0.1, 0.3])
x = x.numpy()
y = np.exp(x) / np.sum(np.exp(x), axis = 0)
z = torch.Tensor([np.exp(0.3), np.exp(0.1), np.exp(0.3)])
a = np.exp(0.3) + np.exp(0.1) + np.exp(0.3)
print(z)
print(y)
print(z / a)



tensor([1.3499, 1.1052, 1.3499])
[0.3547696 0.2904608 0.3547696]
tensor([0.3548, 0.2905, 0.3548])


In [12]:
a = None
print(a)

None


In [33]:
import torch
a = [1]
print(int(a[0]))
b = [2]
# print(zip(a,b))
for i,j in zip(a,b):
    print(j)
x = torch.tensor([12])
y = torch.FloatTensor([13])

print(int(x))
print(int(y))

y = torch.FloatTensor([13,12])
print(max(y))



1
2
12
13
tensor(13.)


In [9]:
def fu(x):
    y = - x ** 2 + x + 1
    return y
X = [0.01 * x for x in range(100)]
Y = [fu(x) for x in X]
print(X)
print(Y)


[0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2, 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3, 0.31, 0.32, 0.33, 0.34, 0.35000000000000003, 0.36, 0.37, 0.38, 0.39, 0.4, 0.41000000000000003, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47000000000000003, 0.48, 0.49, 0.5, 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.5700000000000001, 0.58, 0.59, 0.6, 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.6900000000000001, 0.7000000000000001, 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8, 0.81, 0.8200000000000001, 0.8300000000000001, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9, 0.91, 0.92, 0.93, 0.9400000000000001, 0.9500000000000001, 0.96, 0.97, 0.98, 0.99]
[1.0, 1.0099, 1.0196, 1.0291, 1.0384, 1.0475, 1.0564, 1.0651, 1.0735999999999999, 1.0819, 1.09, 1.0979, 1.1056, 1.1131, 1.1204, 1.1275, 1.1344, 1.1411, 1.1476, 1.1539, 1.16, 1.1659, 1.1716, 1.1771, 1.1824, 1.1875, 1.1924000000000001, 1.1971, 1.2016, 1.2059, 1.21, 1