In [14]:
import torch
x=torch.tensor(3.0)
y=torch.tensor(4)
print(x*y)
a1 = torch.arange(12).reshape(3,4)
print(a1, len(a1), a1.T, a1.shape, a1.shape[1])
print(a1.sum()) #全部加起来

tensor(12.)
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) 3 tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]) torch.Size([3, 4]) 4
tensor(66)


In [4]:
import torch
import numpy as np

x=torch.tensor([[1,2,3,4],[5,6,7,8]])
print(x.numpy())

#随便准备一个网络输入
y = np.array([[3.1, 1.3, 1.2],
              [2.1, 1.3, 13]])
print(y)
z = torch.FloatTensor(y)
print(z)



[[1 2 3 4]
 [5 6 7 8]]
[[ 3.1  1.3  1.2]
 [ 2.1  1.3 13. ]]
tensor([[ 3.1000,  1.3000,  1.2000],
        [ 2.1000,  1.3000, 13.0000]])


In [11]:
import torch
x = torch.Tensor([[1,2], [3,4]])
y = torch.Tensor([[1,2], [3,4]])
print(x * y)


tensor([[ 1.,  4.],
        [ 9., 16.]])


In [7]:
import numpy as np
x = np.array([[1,2,3], 
              [4,5,6]])
y = np.array([[1,2,3], 
              [4,5,6]])
z = np.dot(x,y.T)
a = np.dot(x.T,y)
print(z)
print(a)


[[14 32]
 [32 77]]
[[17 22 27]
 [22 29 36]
 [27 36 45]]


In [10]:
import torch
import numpy as np

x = torch.Tensor([0.3, 0.1, 0.3])
x = x.numpy()
y = np.exp(x) / np.sum(np.exp(x), axis = 0)
z = torch.Tensor([np.exp(0.3), np.exp(0.1), np.exp(0.3)])
a = np.exp(0.3) + np.exp(0.1) + np.exp(0.3)
print(z)
print(y)
print(z / a)



tensor([1.3499, 1.1052, 1.3499])
[0.3547696 0.2904608 0.3547696]
tensor([0.3548, 0.2905, 0.3548])


In [12]:
a = None
print(a)

None


In [33]:
import torch
a = [1]
print(int(a[0]))
b = [2]
# print(zip(a,b))
for i,j in zip(a,b):
    print(j)
x = torch.tensor([12])
y = torch.FloatTensor([13])

print(int(x))
print(int(y))

y = torch.FloatTensor([13,12])
print(max(y))



1
2
12
13
tensor(13.)
