In [3]:
import numpy as np

a = np.array([[1,2,3], [3,4,5],[6,6,6]])
b = np.array([10,11,12])
print(a + b)

[[11 13 15]
 [13 15 17]
 [16 17 18]]


In [10]:
import json
 
# 读取 JSON 文件
with open('data.json', 'r') as f:
    data = json.load(f)
    print(data)
    print(data.get('a', 'aaass'))

{'a': 'xxx'}
xxx


In [4]:
class Person():
    def __init__(self, first, last):
        self.first = first
        self.last = last
        self.fullname = self.first + self.last
    def email(self):
        return self.first + self.last
    @property
    def full(self):
        return self.first + ' ' + self.last

person = Person('zhang', 'san')
print(person.fullname)
print(person.full, 'full')

person.last = 'si'
print(person.fullname) # zhangsan
print(person.email())
print(person.full, 'full1')




zhangsan
zhang san full
zhangsan
zhangsi
zhang si full1


In [ ]:
import torch

tensor1 = torch.FloatTensor([3,4])
tensor1 = torch.nn.functional.normalize(tensor1, dim=-1)
# 每个数都除以所有数的平方和开根号
print(tensor1)


tensor([0.6000, 0.8000])


In [60]:
import torch

a = torch.tensor([2])
print(a.gt(1))
print(torch.sum(a))
b = torch.FloatTensor([1])
c = torch.sum(b)
print(b, 'bbbb')
print(c, 'cccc')
d = c.gt(0)
print(d, 'dddd')
# c = b.diff(1)
print(c.gt(0), 'cccccc')
t = c[c.gt(0)]
print(t, 'tttt') # tensor([3])
print(torch.mean(t))

tensor([True])
tensor(2)
tensor([1.]) bbbb
tensor(1.) cccc
tensor(True) dddd
tensor(True) cccccc
tensor([1.]) tttt
tensor(1.)


In [ ]:
import torch
a = torch.FloatTensor([[2,3,4]])
b = torch.FloatTensor([[3,4,5]])
c = torch.stack((a, b))
print(c, c.shape, 'c') # (1 + 1) * 1 * 3
c = torch.stack((a, b), dim=1)
print(c, c.shape, 'c') # 1 * (1 + 1) * 3




tensor([[[2., 3., 4.]],

        [[3., 4., 5.]]]) torch.Size([2, 1, 3]) c
tensor([[[2., 3., 4.],
         [3., 4., 5.]]]) torch.Size([1, 2, 3]) c


In [4]:
import torch
a = torch.LongTensor([1,2,3])
b = torch.LongTensor([4,5,6])

b = torch.stack([a,b], dim=0)
print(b)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [2]:
import torch
a = torch.FloatTensor([1,2])
c = a.unsqueeze(0)
print(c)

tensor([[1., 2.]])


In [6]:
import torch
a = torch.FloatTensor([[1],[2]])
print(a.shape)
a = a.squeeze()
print(a)
b = torch.FloatTensor([[1,2]])
print(b.squeeze())


torch.Size([2, 1])
tensor([1., 2.])
tensor([1., 2.])


In [3]:
import torch
a = torch.FloatTensor([1,23])
print(a.device)

# 将Tensor移动到GPU上
x = torch.randn(3, 3)
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
x = x.to(device)


cpu


In [3]:
a = [2,3,4]
print(a[-1])
print(a[:-1])



4
[2, 3]


In [3]:
import torch
a = torch.FloatTensor([[1,2,3],[4,5,6]])
b = a.gt(3)
print(b, a)

tensor([[False, False, False],
        [ True,  True,  True]]) tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [5]:
import os
epoch = 10
x = "epoch_%d.pth" % epoch
print(x)
print(os.path.exists('data.json'))


epoch_10.pth
True


In [4]:
import os
print(os.environ.get("HOME"))

/Users/mac


In [7]:
import torch
a = torch.FloatTensor([[1,2], [4,6]])
c = a.cpu().detach().tolist()
print(c)

[[1.0, 2.0], [4.0, 6.0]]


In [21]:
import re
 
it = re.finditer(r"\d+","12 a32bc43jf3")
print(it)
for match in it: 
    print(match.group() + ' a')
    print(match.span())


12 a
(0, 2)
32 a
(4, 6)
43 a
(8, 10)
3 a
(12, 13)


In [ ]:
a = [1,2,3,4,5,6,7,8]
b = [i for i in a if i%2 == 1]
print(b)
print(10 // 3)
for i in range(0,5,2):
    i = i + 1 # 不会影响i
    print(i)


[1, 3, 5, 7]
3
1
3
5
