In [3]:
import numpy as np

a = np.array([[1,2,3], [3,4,5],[6,6,6]])
b = np.array([10,11,12])
print(a + b)

[[11 13 15]
 [13 15 17]
 [16 17 18]]


In [10]:
import json
 
# 读取 JSON 文件
with open('data.json', 'r') as f:
    data = json.load(f)
    print(data)
    print(data.get('a', 'aaass'))

{'a': 'xxx'}
xxx
