In [1]:
import torch

torch.manual_seed(0)

batch1 = torch.randn(10,3,4)
batch2 = torch.randn(10,4,5)

result = torch.bmm(batch1, batch2)
print(result.shape)


torch.Size([10, 3, 5])


In [16]:
import torch

x = torch.FloatTensor([[1,2], [3,4]])
x = x.unsqueeze(0)
print(x)
y = x.size(-1)
print(y)

tensor([[[1., 2.],
         [3., 4.]]])
2


In [23]:
import torch

torch.manual_seed(0)

# 创建一个随机张量
data = torch.randn(10)
print("原始张量:", data)

# 获取前 3 个最大值及其索引
k = 3
values, indices = torch.topk(data,3)
print(f"前 {k} 个最大值:", values)
print(f"最大值的索引:", indices)

print(data.data.topk(1))

原始张量: tensor([ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845, -1.3986,  0.4033,  0.8380,
        -0.7193, -0.4033])
前 3 个最大值: tensor([1.5410, 0.8380, 0.5684])
最大值的索引: tensor([0, 7, 3])
tensor([1.5410])


In [1]:
import torch

cuda_flag = torch.cuda.is_available()
print(cuda_flag)


False


In [1]:
import torch
a = 97
b = 10
print(a // b)
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6]])
mask = torch.FloatTensor([[1, 0, 0], 
                          [1, 1, 0]])
t = torch.masked_fill(x, mask == 0, value=0)
print(t)
print(mask.unsqueeze(1).unsqueeze(2))

9
tensor([[1., 0., 0.],
        [4., 5., 0.]])
tensor([[[[1., 0., 0.]]],


        [[[1., 1., 0.]]]])


In [6]:
import torch
x = torch.FloatTensor([[[ 0.,  1.,  2.],
                        [ 3.,  4.,  5.]],
                        [[ 6.,  7.,  8.],
                        [ 9., 10., 11.]]])
print(x.shape)
a = x.transpose(-2,-1)
print(a)
b = x.transpose(1,2)
print(b)




torch.Size([2, 2, 3])
tensor([[[ 0.,  3.],
         [ 1.,  4.],
         [ 2.,  5.]],

        [[ 6.,  9.],
         [ 7., 10.],
         [ 8., 11.]]])
tensor([[[ 0.,  3.],
         [ 1.,  4.],
         [ 2.,  5.]],

        [[ 6.,  9.],
         [ 7., 10.],
         [ 8., 11.]]])


In [2]:
import torch
torch.manual_seed(1)
x = torch.randn((2,3))
print(x)

mask = torch.tril(torch.ones((x.shape[0], x.shape[1], x.shape[1])))
print(mask)


tensor([[ 0.6614,  0.2669,  0.0617],
        [ 0.6213, -0.4519, -0.1661]])
tensor([[[1., 0., 0.],
         [1., 1., 0.],
         [1., 1., 1.]],

        [[1., 0., 0.],
         [1., 1., 0.],
         [1., 1., 1.]]])


In [6]:
import torch
a = torch.FloatTensor([[1,2,3], [4,5,6],[7,8,9]])
print(a.view(9,-1))

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


In [22]:
import torch
prompt_encode = 5 + 2
answer_encode = 3 + 1
size = prompt_encode + answer_encode
res = torch.ones(size, size)
for i in range(size):
    if i < prompt_encode:
        res[i, prompt_encode:] = 0

print(res)




tensor([[1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [21]:
import torch
a = [[0,1],[2,4]]
b = torch.FloatTensor(a)
b[0,:] = b[0,:] + 0.1
print(b)

tensor([[0.1000, 1.1000],
        [2.0000, 4.0000]])
