In [1]:
import torch

torch.manual_seed(0)

batch1 = torch.randn(10,3,4)
batch2 = torch.randn(10,4,5)

result = torch.bmm(batch1, batch2)
print(result.shape)


torch.Size([10, 3, 5])


In [16]:
import torch

x = torch.FloatTensor([[1,2], [3,4]])
x = x.unsqueeze(0)
print(x)
y = x.size(-1)
print(y)

tensor([[[1., 2.],
         [3., 4.]]])
2


In [23]:
import torch

torch.manual_seed(0)

# 创建一个随机张量
data = torch.randn(10)
print("原始张量:", data)

# 获取前 3 个最大值及其索引
k = 3
values, indices = torch.topk(data,3)
print(f"前 {k} 个最大值:", values)
print(f"最大值的索引:", indices)

print(data.data.topk(1))

原始张量: tensor([ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845, -1.3986,  0.4033,  0.8380,
        -0.7193, -0.4033])
前 3 个最大值: tensor([1.5410, 0.8380, 0.5684])
最大值的索引: tensor([0, 7, 3])
tensor([1.5410])


In [1]:
import torch

cuda_flag = torch.cuda.is_available()
print(cuda_flag)


False


In [1]:
import torch
a = 97
b = 10
print(a // b)
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6]])
mask = torch.FloatTensor([[1, 0, 0], 
                          [1, 1, 0]])
t = torch.masked_fill(x, mask == 0, value=0)
print(t)
print(mask.unsqueeze(1).unsqueeze(2))

9
tensor([[1., 0., 0.],
        [4., 5., 0.]])
tensor([[[[1., 0., 0.]]],


        [[[1., 1., 0.]]]])


In [6]:
import torch
x = torch.FloatTensor([[[ 0.,  1.,  2.],
                        [ 3.,  4.,  5.]],
                        [[ 6.,  7.,  8.],
                        [ 9., 10., 11.]]])
print(x.shape)
a = x.transpose(-2,-1)
print(a)
b = x.transpose(1,2)
print(b)




torch.Size([2, 2, 3])
tensor([[[ 0.,  3.],
         [ 1.,  4.],
         [ 2.,  5.]],

        [[ 6.,  9.],
         [ 7., 10.],
         [ 8., 11.]]])
tensor([[[ 0.,  3.],
         [ 1.,  4.],
         [ 2.,  5.]],

        [[ 6.,  9.],
         [ 7., 10.],
         [ 8., 11.]]])
