In [3]:
import torch
a = torch.tensor([1,23])
b = a.unsqueeze(0)
print(b)
# tensor([[ 1, 23]])

tensor([[ 1, 23]])


In [5]:
import torch
a = torch.rand(3,2)
print(a)

tensor([[0.5890, 0.0322],
        [0.6737, 0.5767],
        [0.8653, 0.9976]])


In [7]:
import  torch
x = torch.rand(3,4,5)
y = x.transpose(1,2)
print(x, '初始化')
print(y,'交换后')


tensor([[[0.1556, 0.0488, 0.6749, 0.8657, 0.3957],
         [0.8787, 0.7067, 0.7836, 0.2523, 0.7019],
         [0.0559, 0.4810, 0.0908, 0.0820, 0.0575],
         [0.3082, 0.0847, 0.6945, 0.9757, 0.3815]],

        [[0.1920, 0.7042, 0.1238, 0.3902, 0.3674],
         [0.1378, 0.5853, 0.9951, 0.1558, 0.7743],
         [0.6527, 0.3262, 0.7607, 0.2180, 0.4091],
         [0.9657, 0.1866, 0.8723, 0.5388, 0.6810]],

        [[0.4814, 0.2802, 0.5671, 0.5053, 0.5056],
         [0.6082, 0.9166, 0.8222, 0.3504, 0.6717],
         [0.0653, 0.3577, 0.9621, 0.9755, 0.3694],
         [0.4177, 0.3209, 0.8680, 0.8084, 0.8840]]]) 初始化
tensor([[[0.1556, 0.8787, 0.0559, 0.3082],
         [0.0488, 0.7067, 0.4810, 0.0847],
         [0.6749, 0.7836, 0.0908, 0.6945],
         [0.8657, 0.2523, 0.0820, 0.9757],
         [0.3957, 0.7019, 0.0575, 0.3815]],

        [[0.1920, 0.1378, 0.6527, 0.9657],
         [0.7042, 0.5853, 0.3262, 0.1866],
         [0.1238, 0.9951, 0.7607, 0.8723],
         [0.3902, 0.1558, 0.2180

In [10]:
import numpy as np
x = np.array([[1, 2, 3], [4,5,6]])
y = np.array([[1, 2, 3], [4,5,6]])
z = np.dot(x.T,y)
print(z)


[[17 22 27]
 [22 29 36]
 [27 36 45]]


In [96]:
import math
import torch
# print(math.exp(1))
a  =1e1
print(a)
x = np.array([[1, 2, 3], [4,5,6]])
y = torch.Tensor(x)
print(y)
print(torch.mean(y, axis=0))
print(torch.mean(y, axis=1))
x = torch.Tensor([5,4,1,1,1])
z = torch.Tensor([1,2,3,4,5])
t = torch.Tensor([1,2])
a = torch.Tensor([[1,2,3,4,5]]) # 1 * 5
b = torch.Tensor([[1,2,3,4,5], [1,1,1,2,3]]) # 1 * 5

# print(y * x)
print(x * z, 'x * z')
print(a * b, 'a * b')
# print(z * t, 'z * t') #报错
a2 = torch.FloatTensor([[1.5,  0.02, -1.67979825, -0.40878469, -0.15948112],
 [-0.2,  1.46404247, 0.16369624, 1.69176915, -1.43420591],
 [-1.1, -0.13, 0.73548213, -0.37072311, 0.22804862],
 [-0.13063803, -1.35548882, 0.78061989, -0.91226135, 1.36563841]])
print(x * a2)



10.0
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])
tensor([5., 8., 3., 4., 5.]) x * z
tensor([[ 1.,  4.,  9., 16., 25.],
        [ 1.,  2.,  3.,  8., 15.]]) a * b
tensor([[ 7.5000,  0.0800, -1.6798, -0.4088, -0.1595],
        [-1.0000,  5.8562,  0.1637,  1.6918, -1.4342],
        [-5.5000, -0.5200,  0.7355, -0.3707,  0.2280],
        [-0.6532, -5.4220,  0.7806, -0.9123,  1.3656]])


In [94]:
a = '111'
b = 3
c = 2
# print(b & c) #按位与， |按位或，^按位异或
all = 'abcd'
ran = 'ba'
print('set(all)',set(all))
print(set(ran) & set(all))
if (set()):
    print(1)
else:
    print(2)

set(all) {'d', 'c', 'b', 'a'}
{'b', 'a'}
2


In [101]:
import torch
x = torch.Tensor([
    [3,4],
    [6,5]
])
y = torch.Tensor([4,3,44,1])
max_value, max_index = torch.max(x, dim=1)
print("最大值:", max_value)
print("最大值的索引:", max_index)
print(torch.max(y))


最大值: tensor([4., 6.])
最大值的索引: tensor([1, 0])
tensor(44.)


In [130]:
import random
random_number = random.randint(0, 5)
print(random_number)

5


In [135]:
import copy
origin = { 'a': 1, 'b': 2}
c = copy.deepcopy(origin)
t = 'a'
c.pop(t)
print(c)
print(origin)



{'b': 2}
{'a': 1, 'b': 2}


In [137]:
import torch
tensor = torch.randn(2, 3)
print(tensor.numpy())
t = torch.Tensor([[2,3], [4,5]])
print(t.numpy())


[[ 0.19195469  0.26557204 -0.29543218]
 [-1.2182368  -0.1580241  -0.4663215 ]]
[[2. 3.]
 [4. 5.]]
